development:
  host: http://localhost:3000
  #host: http://127.0.0.1:3000
  handle: kitchen-sink-template
  email: user@example.com
  api_key: <your api key here>

staging:
  host: staging-cms.example.com
  email: user@example.com
  handle: kitchen-sink-template
  api_key: <your api key here>

production:
  host: production-cms.example.com
  email: user@example.com
  handle: kitchen-sink-template
  api_key: <your api key here>
  ssl: true
