##### Site metafield schema #####

### EXAMPLE
# general: # no spaces, only digits and underscores
#   label: # if you want to provide the label in another language (back-office)
#     en: 'General Stuff' 
#   fields:
#     company_name:
#       label: 'Company Name' # used as the label of the HTML input. Use a hash if you want it in another languages.
#       hint: 'Lorem Ipsum...' # used as the hint of the HTML input. Use a hash if you want it in another languages.
#       type: string # <string|text|integer|float|image|boolean|select|color>
#       localized: false # if the value is scoped by the current locale when rendering the site.
#       position: 0 # <0..n>, position of the input in the form
#       select_options: [array]
#       # select_options:
#       #   <option_value_1>: <label> # use a hash instead if you want it in another languages.
#       #   <option_value_2>: <label> # use a hash instead if you want it in another languages.
#     # other_field:
#     #   ...
#
# theme:
#   # ...
#
### EXAMPLE END

company:
  label: 'Company'
  fields:
    name:
      type: string
      sample: My Company
    address:
      type: string
      sample: 1234 Smith St
    city:
      type: string
      sample: Vancouver, BC, Canada
    postal_code:
      type: string
      sample: V5K 0A1
    phone:
      type: string
      sample: (123)-456-7890
    email:
      type: string
      sample: info@mycompany.com
    hours:
      type: text
      sample: "Monday to Friday<br>9am - 5pm"

theme:
  label: 'Theme'
  fields:
    background_color:
      type: color
    background_image:
      type: image
      hint: "full screen background image (min: 3000px x 3000px)"
    main_link_color:
      type: color
    font:
      type: select
      select_options: ['helvetica', 'Noto']

social:
  label: Social networks
  fields:
    - facebook
    - twitter
    - linkedin
    - pinterest
    - dribbble
    - instagram

email_settings:
  label: "Email SMTP Settings"
  fields:
    smtp_host:
      type: string
    smtp_post:
      type: string
    smtp_user:
      type: string
    smtp_password:
      type: string
    authentication:
      type: string
      sample: plain
    enable_starttls_auto: 
      type: boolean
      sample: true
